const products = [
    {
        title: 'White shirt',
        img: './images/WhiteShirt.png',
        description: 'white cotton shirt',
        options: [],
        type: 'superior garments',
        color: 'white',
        price: 28000,
    },
 {
title: 'Green dress',
        img: './images/GreenDress.png',
        description: 'green satin dress',
        options: [],
        type:'dresses',
        color: 'green',
        price: 40000,
    },
{
title: 'Black shirt',
        img: './images/BlackShirt.png',
        description: 'black cotton shirt',
        options: [],
        type:'lower prendsas  ',
        color: 'black',
        price: 28000,
    },
{
title: 'Wine red skirt',
        img: './images/WineRedSkirt.png',
        description: 'wine red leather skirt',
        options: [],
        type: 'superior garments',
        color: 'wine red',
        price: 50000,
    },
{
title: 'Gray diver',
        img: './images/GrayDiver.png',
        description: 'gray cotton diver',
        options: [],
        type:'superior garments',
        color: 'gray',
        price: 50000,
    },
{
title: 'Green jacket',
        img: './images/GreenJacket.png',
        description: 'green leather jacket',
        options: [],
        type:'superior garments',
        color: 'green',
        price: 40000,
    },
{
title: 'Waterproof green jacket',
        img: './images/WaterproogGreenJacket.png',
        description: 'green waterproog jacket',
        options: [],
        type:'superior garments',
        color: 'green',
        price: 60000,
    },
{
title: 'Black overalls',
        img: './images/BlackOveralls.png',
        description: 'black cotton overralls',
        options: [],
        type: 'lower prendsas'  ,
        color: 'black',
        price: 120000,
    },
{
title: 'White diver',
        img: './images/WhiteDiver.png',
        description: 'white cotton diver',
        options: [],
        type:'superior garments',
        color: 'white',
        price: 70000,
    },
{
title: 'Transparent black dress',
        img: './images/TransparentBlackDress.png',
        description: 'black tulle dress',
        options: [],
        type:'dresses',
        color: 'black',
        price: 40000,
    },
{
title: 'Yellow diver',
        img: './images/YellowDiver.png',
        description: 'Yellow cotton diver',
        options: [],
        type:'superior garments',
        color: 'yellow',
        price: 80000,
    },
{
title: 'Green pants',
        img: './images/GreenPants.png',
        description: 'Green cotton pants',
        options: [],
        type:'lower prendsas  ',
        color: 'green',
        price: 40000,
    },
{
title: 'Black and Yellow jacket',
        img: './images/Black&YellowJacket.png',
        description: 'Black and yellow - jacket',
        options: [],
        type:'superior garments',
        color: 'yellow',
        price: 50000,
    },
{
title: 'Transparent black pants',
        img: './images/TransparentBlackPants.png',
        description: 'Black mesh pants',
        options: [],
        type:'lower prendsas ',
        color: 'black',
        price: 60000,
    },
{
title: 'Green diver',
        img: './images/GreenDriver.png',
        description: 'green cotton diver',
        options: [],
        type:'superior garments',
        color: 'green',
        price: 70000,
    },
{
title: 'Brown plaid pants',
        img: './images/BrownPlaidPants.png',
        description: 'brownk cotton pants',
        options: [],
        type:'lower prendsas ',
        color: 'brown',
        price: 70000,
    },
{
title: 'Red plaid skirt',
        img: './images/RedPlaidSkirt.png',
        description: 'red cotton skirt',
        options: [],
        type:'lower prendsas ',
        color: 'red',
        price: 50000,
    },

{
    title: 'Red diver',
        img: './images/RedDiver.png',
        description: 'Red cotton diver',
        options: [],
        type:'superior garments',
        color: 'red',
        price: 40000,
    },
        
{
title: 'Blue dress',
        img: './images/BlueDress.png',
        description: 'blue jean dress',
        options: [],
        type:'dresses',
        color: 'blue',
        price: 60000,
    },
{
title: 'White plaid skirt',
        img: './images/WhitePlaidSkirt.png',
        description: 'white cotton skirt',
        options: [],
        type:'lower prendsas ',
        color: 'white',
        price: 55000,
    },
{
title: 'Gray plaid pants',
        img: './images/GrayPlaidPants.png',
        description: 'grey cotton pants',
        options: [],
        type:'lower prendsas ',
        color: 'grey',
        price: 70000,
    },

];